site_name: UglyChain
site_url: https://uglychain.uglyboy.cn
repo_name: uglyboy-tl/uglychain
repo_url: https://github.com/uglyboy-tl/uglychain

theme:
  name: material
  language: 'zh'  # 配置语言
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
  icon:
    repo: fontawesome/brands/github
site_url: https://uglyboy-tl.github.io/UglyChain/

nav:
  - 主页:
    - 介绍: index.md
    - 快速开始: quickstart.md
    - 配置: config.md
    - 例子: examples.md
  - Chain:
    - LLM: Chain/llm.md
    - MapChain: Chain/mapchain.md
    - ReduceChain: Chain/reducechain.md
    - ReActChain: Chain/reactchain.md
  - Agent:
    - Structured : Agent/structured.md
    - Tools: Agent/tools.md
    - ReAct: Agent/react.md
    - Retriever: Agent/retriever.md
  - Worker:
    - Base: Worker/worker.md
    - Classify: Worker/classify.md
    - Summary: Worker/summary.md
    - Code Interpreter: Worker/ci.md
    - Plan: Worker/plan.md
  - 关于: about.md

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.highlight:
      linenums: true
      anchor_linenums: true
      auto_title: true
      line_spans: __span
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true

plugins:
  - git-revision-date