site_name: UglyChain
site_url: https://uglychain.uglyboy.cn
repo_name: uglyboy-tl/uglychain
repo_url: https://github.com/uglyboy-tl/uglychain

theme:
  name: material
  language: 'zh'  # 配置语言
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
  icon:
    repo: fontawesome/brands/github
site_url: https://uglyboy-tl.github.io/UglyChain/

nav:
  - 主页:
    - 介绍: index.md
    - 快速开始: quickstart.md
    - 路线图: roadmap.md
  - 入门:
    - 安装: install.md
    - 配置: config.md
  - Chain:
    - LLM: Chain/llm.md
    - MapChain: Chain/mapchain.md
    - ReduceChain: Chain/reducechain.md
  - Agent:
    - Tools: Agent/tools.md
    - ReAct: Agent/react.md
    - Retriever: Agent/retriever.md
  - Worker:
    - Base: Worker/worker.md
    - Summary: Worker/summary.md
    - Classify: Worker/classify.md
    - Plan: Worker/plan.md
    - Code Interpreter: Worker/ci.md
    - Code: Worker/code.md
    - Continue: Worker/continue.md
  - 参考: examples.md
  - 关于: about.md

markdown_extensions:
  - toc:
      permalink: true

plugins:
  - git-revision-date