site_name: UglyChain
theme:
  name: material
site_url: https://uglyboy-tl.github.io/UglyChain/

nav:
  - Home: index.md
  - Install: install.md
  - Documents:
    - Introduction: introduction.md
    - Quick Start: quickstart.md
    - Examples: examples.md
    - LLM: llm.md
    - Chain: chain.md
    - Tools: tools.md