name: Release

on:
  release:
    types: [published]
  workflow_dispatch:  # 允许手动触发

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install PDM
        run: pip install pdm

      - name: Get version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update pyproject.toml version
        run: |
          sed -i "s/^version = .*/version = \"${{ steps.get_version.outputs.version }}\"/" pyproject.toml

      - name: Update __init__.py version
        run: |
          sed -i "s/^__version__ = .*/__version__ = \"${{ steps.get_version.outputs.version }}\"/" src/uglychain/__init__.py

      - name: Configure git
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit version updates
        run: |
          git add pyproject.toml src/uglychain/__init__.py
          git commit -m "Bump version to ${{ steps.get_version.outputs.version }}"
          git push origin HEAD:main

      - name: Publish with PDM
        run: pdm publish
        env:
          PDM_PYPI_USERNAME: ${{ secrets.PYPI_USERNAME }}
          PDM_PYPI_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
