name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: 安装 uv
        uses: astral-sh/setup-uv@v6
        with:
          enable-cache: true

      - name: "安装 Python"
        uses: actions/setup-python@v5
        with:
          python-version-file: ".python-version"

      - name: "构建"
        run: uv build
        env:
          UV_CACHE_DIR: ${{ github.workspace }}/.uv-cache

      - name: "发布到 PyPI"
        run: uv publish
