name: Release

on:
  release:
    types: [published]

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: pdm-project/setup-pdm@v4

      - name: Get version from tag
        id: get_version
        run: echo "version=${GITHUB_REF#refs/tags/v}" >> $GITHUB_OUTPUT

      - name: Update pyproject.toml version
        run: |
          sed -i "s/^version = .*/version = \"${{ steps.get_version.outputs.version }}\"/" pyproject.toml

      - name: Update __init__.py version
        run: |
          sed -i "s/^__version__ = .*/__version__ = \"${{ steps.get_version.outputs.version }}\"/" src/uglychain/__init__.py

      - name: Commit version updates
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml src/uglychain/__init__.py
          git commit -m "Bump version to ${{ steps.get_version.outputs.version }}"
          git push origin HEAD:main

      - name: Publish with PDM
        run: pdm publish
