name: Release From Tag

on:
  push:
    tags:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout with full history
        uses: actions/checkout@v4
        with:
          ref: main
          fetch-depth: 0  # 获取完整提交历史

      - name: Update version files
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          sed -i "s/^version = .*/version = \"$tag\"/" pyproject.toml
          sed -i "s/^__version__ = .*/__version__ = \"$tag\"/" src/uglychain/__init__.py

      - name: Commit changes
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add -u
          git commit -m "Update version to $tag" || echo "No changes to commit"
          git push origin HEAD:main

      - name: Reassign tag
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          # 强制将 tag 移动到最新提交
          git tag -f "$tag"
          git push origin -f "$tag"

      - name: Create Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          tag="${GITHUB_REF#refs/tags/}"
          # 直接使用 main 分支的最新提交
          gh release create "$tag" \
            --target main \
            --title "$tag" \
            --generate-notes \
            --draft
